# Generated by Django 3.0.6 on 2020-07-28 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0002_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
